#############################################################################
# Makefile for building: FractalCrypt
# Generated by qmake (3.1) (Qt 5.15.3)
# Project:  FractalCrypt.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile FractalCrypt.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQUAZIP_STATIC -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = FractalCrypt1.0.0
DISTDIR = /home/ares/Projects/FractalCryptGUI/.tmp/FractalCrypt1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) -largon2 -ldl -lz -lcrypto /usr/lib/x86_64-linux-gnu/libQt5Widgets.so /usr/lib/x86_64-linux-gnu/libQt5Gui.so /usr/lib/x86_64-linux-gnu/libQt5Core.so -lGL -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		core/aes.cpp \
		core/directorysizecalculator.cpp \
		core/fractalcryptcore.cpp \
		core/quazipfunctions.cpp \
		widgets/archivewindow.cpp \
		widgets/createcontainerwindow.cpp \
		widgets/mainwindow.cpp \
		widgets/progressdialog.cpp \
		widgets/resizecontainerwindow.cpp \
		widgets/startwindow.cpp \
		quazip/JlCompress.cpp \
		quazip/qioapi.cpp \
		quazip/quaadler32.cpp \
		quazip/quacrc32.cpp \
		quazip/quagzipfile.cpp \
		quazip/quaziodevice.cpp \
		quazip/quazip.cpp \
		quazip/quazipdir.cpp \
		quazip/quazipfile.cpp \
		quazip/quazipfileinfo.cpp \
		quazip/quazipnewinfo.cpp \
		quazip/unzip.c \
		quazip/zip.c qrc_resources.cpp \
		moc_aes.cpp \
		moc_directorysizecalculator.cpp \
		moc_noizecreator.cpp \
		moc_archivewindow.cpp \
		moc_createcontainerwindow.cpp \
		moc_resizecontainerwindow.cpp \
		moc_startwindow.cpp \
		moc_mainwindow.cpp \
		moc_progressdialog.cpp \
		moc_quagzipfile.cpp \
		moc_quaziodevice.cpp \
		moc_quazipfile.cpp
OBJECTS       = main.o \
		aes.o \
		directorysizecalculator.o \
		fractalcryptcore.o \
		quazipfunctions.o \
		archivewindow.o \
		createcontainerwindow.o \
		mainwindow.o \
		progressdialog.o \
		resizecontainerwindow.o \
		startwindow.o \
		JlCompress.o \
		qioapi.o \
		quaadler32.o \
		quacrc32.o \
		quagzipfile.o \
		quaziodevice.o \
		quazip.o \
		quazipdir.o \
		quazipfile.o \
		quazipfileinfo.o \
		quazipnewinfo.o \
		unzip.o \
		zip.o \
		qrc_resources.o \
		moc_aes.o \
		moc_directorysizecalculator.o \
		moc_noizecreator.o \
		moc_archivewindow.o \
		moc_createcontainerwindow.o \
		moc_resizecontainerwindow.o \
		moc_startwindow.o \
		moc_mainwindow.o \
		moc_progressdialog.o \
		moc_quagzipfile.o \
		moc_quaziodevice.o \
		moc_quazipfile.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		FractalCrypt.pro core/aes.h \
		core/argon2.h \
		core/directorysizecalculator.h \
		core/fractalcryptcore.h \
		core/noizecreator.hpp \
		core/quazipfunctions.h \
		widgets/archivewindow.h \
		widgets/createcontainerwindow.h \
		widgets/resizecontainerwindow.h \
		widgets/startwindow.h \
		widgets/mainwindow.h \
		widgets/progressdialog.h \
		quazip/JlCompress.h \
		quazip/crypt.h \
		quazip/ioapi.h \
		quazip/quaadler32.h \
		quazip/quachecksum32.h \
		quazip/quacrc32.h \
		quazip/quagzipfile.h \
		quazip/quaziodevice.h \
		quazip/quazip.h \
		quazip/quazip_global.h \
		quazip/quazipdir.h \
		quazip/quazipfile.h \
		quazip/quazipfileinfo.h \
		quazip/quazipnewinfo.h \
		quazip/unzip.h \
		quazip/zip.h main.cpp \
		core/aes.cpp \
		core/directorysizecalculator.cpp \
		core/fractalcryptcore.cpp \
		core/quazipfunctions.cpp \
		widgets/archivewindow.cpp \
		widgets/createcontainerwindow.cpp \
		widgets/mainwindow.cpp \
		widgets/progressdialog.cpp \
		widgets/resizecontainerwindow.cpp \
		widgets/startwindow.cpp \
		quazip/JlCompress.cpp \
		quazip/qioapi.cpp \
		quazip/quaadler32.cpp \
		quazip/quacrc32.cpp \
		quazip/quagzipfile.cpp \
		quazip/quaziodevice.cpp \
		quazip/quazip.cpp \
		quazip/quazipdir.cpp \
		quazip/quazipfile.cpp \
		quazip/quazipfileinfo.cpp \
		quazip/quazipnewinfo.cpp \
		quazip/unzip.c \
		quazip/zip.c
QMAKE_TARGET  = FractalCrypt
DESTDIR       = 
TARGET        = FractalCrypt


first: all
####### Build rules

FractalCrypt: ui_archivewindow.h ui_createcontainerwindow.h ui_mainwindow.h ui_progressdialog.h ui_resizecontainerwindow.h ui_startwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: FractalCrypt.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		FractalCrypt.pro \
		resources.qrc
	$(QMAKE) -o Makefile FractalCrypt.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
FractalCrypt.pro:
resources.qrc:
qmake: FORCE
	@$(QMAKE) -o Makefile FractalCrypt.pro

qmake_all: FORCE


all: Makefile FractalCrypt

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents resources.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents core/aes.h core/argon2.h core/directorysizecalculator.h core/fractalcryptcore.h core/noizecreator.hpp core/quazipfunctions.h widgets/archivewindow.h widgets/createcontainerwindow.h widgets/resizecontainerwindow.h widgets/startwindow.h widgets/mainwindow.h widgets/progressdialog.h quazip/JlCompress.h quazip/crypt.h quazip/ioapi.h quazip/quaadler32.h quazip/quachecksum32.h quazip/quacrc32.h quazip/quagzipfile.h quazip/quaziodevice.h quazip/quazip.h quazip/quazip_global.h quazip/quazipdir.h quazip/quazipfile.h quazip/quazipfileinfo.h quazip/quazipnewinfo.h quazip/unzip.h quazip/zip.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp core/aes.cpp core/directorysizecalculator.cpp core/fractalcryptcore.cpp core/quazipfunctions.cpp widgets/archivewindow.cpp widgets/createcontainerwindow.cpp widgets/mainwindow.cpp widgets/progressdialog.cpp widgets/resizecontainerwindow.cpp widgets/startwindow.cpp quazip/JlCompress.cpp quazip/qioapi.cpp quazip/quaadler32.cpp quazip/quacrc32.cpp quazip/quagzipfile.cpp quazip/quaziodevice.cpp quazip/quazip.cpp quazip/quazipdir.cpp quazip/quazipfile.cpp quazip/quazipfileinfo.cpp quazip/quazipnewinfo.cpp quazip/unzip.c quazip/zip.c $(DISTDIR)/
	$(COPY_FILE) --parents ui/archivewindow.ui ui/createcontainerwindow.ui ui/mainwindow.ui ui/progressdialog.ui ui/resizecontainerwindow.ui ui/startwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resources.cpp
qrc_resources.cpp: resources.qrc \
		/usr/lib/qt5/bin/rcc \
		logo.png
	/usr/lib/qt5/bin/rcc -name resources resources.qrc -o qrc_resources.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -std=gnu++11 -Wall -Wextra -dM -E -o moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_aes.cpp moc_directorysizecalculator.cpp moc_noizecreator.cpp moc_archivewindow.cpp moc_createcontainerwindow.cpp moc_resizecontainerwindow.cpp moc_startwindow.cpp moc_mainwindow.cpp moc_progressdialog.cpp moc_quagzipfile.cpp moc_quaziodevice.cpp moc_quazipfile.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_aes.cpp moc_directorysizecalculator.cpp moc_noizecreator.cpp moc_archivewindow.cpp moc_createcontainerwindow.cpp moc_resizecontainerwindow.cpp moc_startwindow.cpp moc_mainwindow.cpp moc_progressdialog.cpp moc_quagzipfile.cpp moc_quaziodevice.cpp moc_quazipfile.cpp
moc_aes.cpp: core/aes.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/ares/Projects/FractalCryptGUI/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/ares/Projects/FractalCryptGUI -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include core/aes.h -o moc_aes.cpp

moc_directorysizecalculator.cpp: core/directorysizecalculator.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/ares/Projects/FractalCryptGUI/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/ares/Projects/FractalCryptGUI -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include core/directorysizecalculator.h -o moc_directorysizecalculator.cpp

moc_noizecreator.cpp: core/noizecreator.hpp \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/ares/Projects/FractalCryptGUI/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/ares/Projects/FractalCryptGUI -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include core/noizecreator.hpp -o moc_noizecreator.cpp

moc_archivewindow.cpp: widgets/archivewindow.h \
		core/fractalcryptcore.h \
		core/quazipfunctions.h \
		quazip/quazip.h \
		quazip/zip.h \
		quazip/ioapi.h \
		quazip/unzip.h \
		quazip/quazip_global.h \
		quazip/quazipfileinfo.h \
		quazip/quazipfile.h \
		quazip/quazipnewinfo.h \
		quazip/quazipdir.h \
		quazip/JlCompress.h \
		core/aes.h \
		core/noizecreator.hpp \
		widgets/progressdialog.h \
		core/directorysizecalculator.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/ares/Projects/FractalCryptGUI/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/ares/Projects/FractalCryptGUI -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include widgets/archivewindow.h -o moc_archivewindow.cpp

moc_createcontainerwindow.cpp: widgets/createcontainerwindow.h \
		core/fractalcryptcore.h \
		core/quazipfunctions.h \
		quazip/quazip.h \
		quazip/zip.h \
		quazip/ioapi.h \
		quazip/unzip.h \
		quazip/quazip_global.h \
		quazip/quazipfileinfo.h \
		quazip/quazipfile.h \
		quazip/quazipnewinfo.h \
		quazip/quazipdir.h \
		quazip/JlCompress.h \
		core/aes.h \
		core/noizecreator.hpp \
		widgets/progressdialog.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/ares/Projects/FractalCryptGUI/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/ares/Projects/FractalCryptGUI -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include widgets/createcontainerwindow.h -o moc_createcontainerwindow.cpp

moc_resizecontainerwindow.cpp: widgets/resizecontainerwindow.h \
		core/fractalcryptcore.h \
		core/quazipfunctions.h \
		quazip/quazip.h \
		quazip/zip.h \
		quazip/ioapi.h \
		quazip/unzip.h \
		quazip/quazip_global.h \
		quazip/quazipfileinfo.h \
		quazip/quazipfile.h \
		quazip/quazipnewinfo.h \
		quazip/quazipdir.h \
		quazip/JlCompress.h \
		core/aes.h \
		core/noizecreator.hpp \
		widgets/progressdialog.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/ares/Projects/FractalCryptGUI/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/ares/Projects/FractalCryptGUI -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include widgets/resizecontainerwindow.h -o moc_resizecontainerwindow.cpp

moc_startwindow.cpp: widgets/startwindow.h \
		widgets/createcontainerwindow.h \
		core/fractalcryptcore.h \
		core/quazipfunctions.h \
		quazip/quazip.h \
		quazip/zip.h \
		quazip/ioapi.h \
		quazip/unzip.h \
		quazip/quazip_global.h \
		quazip/quazipfileinfo.h \
		quazip/quazipfile.h \
		quazip/quazipnewinfo.h \
		quazip/quazipdir.h \
		quazip/JlCompress.h \
		core/aes.h \
		core/noizecreator.hpp \
		widgets/progressdialog.h \
		widgets/mainwindow.h \
		widgets/archivewindow.h \
		core/directorysizecalculator.h \
		widgets/resizecontainerwindow.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/ares/Projects/FractalCryptGUI/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/ares/Projects/FractalCryptGUI -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include widgets/startwindow.h -o moc_startwindow.cpp

moc_mainwindow.cpp: widgets/mainwindow.h \
		widgets/createcontainerwindow.h \
		core/fractalcryptcore.h \
		core/quazipfunctions.h \
		quazip/quazip.h \
		quazip/zip.h \
		quazip/ioapi.h \
		quazip/unzip.h \
		quazip/quazip_global.h \
		quazip/quazipfileinfo.h \
		quazip/quazipfile.h \
		quazip/quazipnewinfo.h \
		quazip/quazipdir.h \
		quazip/JlCompress.h \
		core/aes.h \
		core/noizecreator.hpp \
		widgets/progressdialog.h \
		widgets/archivewindow.h \
		core/directorysizecalculator.h \
		widgets/resizecontainerwindow.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/ares/Projects/FractalCryptGUI/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/ares/Projects/FractalCryptGUI -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include widgets/mainwindow.h -o moc_mainwindow.cpp

moc_progressdialog.cpp: widgets/progressdialog.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/ares/Projects/FractalCryptGUI/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/ares/Projects/FractalCryptGUI -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include widgets/progressdialog.h -o moc_progressdialog.cpp

moc_quagzipfile.cpp: quazip/quagzipfile.h \
		quazip/quazip_global.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/ares/Projects/FractalCryptGUI/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/ares/Projects/FractalCryptGUI -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include quazip/quagzipfile.h -o moc_quagzipfile.cpp

moc_quaziodevice.cpp: quazip/quaziodevice.h \
		quazip/quazip_global.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/ares/Projects/FractalCryptGUI/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/ares/Projects/FractalCryptGUI -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include quazip/quaziodevice.h -o moc_quaziodevice.cpp

moc_quazipfile.cpp: quazip/quazipfile.h \
		quazip/quazip_global.h \
		quazip/quazip.h \
		quazip/zip.h \
		quazip/ioapi.h \
		quazip/unzip.h \
		quazip/quazipfileinfo.h \
		quazip/quazipnewinfo.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/ares/Projects/FractalCryptGUI/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/ares/Projects/FractalCryptGUI -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include quazip/quazipfile.h -o moc_quazipfile.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_archivewindow.h ui_createcontainerwindow.h ui_mainwindow.h ui_progressdialog.h ui_resizecontainerwindow.h ui_startwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_archivewindow.h ui_createcontainerwindow.h ui_mainwindow.h ui_progressdialog.h ui_resizecontainerwindow.h ui_startwindow.h
ui_archivewindow.h: ui/archivewindow.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic ui/archivewindow.ui -o ui_archivewindow.h

ui_createcontainerwindow.h: ui/createcontainerwindow.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic ui/createcontainerwindow.ui -o ui_createcontainerwindow.h

ui_mainwindow.h: ui/mainwindow.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic ui/mainwindow.ui -o ui_mainwindow.h

ui_progressdialog.h: ui/progressdialog.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic ui/progressdialog.ui -o ui_progressdialog.h

ui_resizecontainerwindow.h: ui/resizecontainerwindow.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic ui/resizecontainerwindow.ui -o ui_resizecontainerwindow.h

ui_startwindow.h: ui/startwindow.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic ui/startwindow.ui -o ui_startwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp core/fractalcryptcore.h \
		core/quazipfunctions.h \
		quazip/quazip.h \
		quazip/zip.h \
		quazip/ioapi.h \
		quazip/unzip.h \
		quazip/quazip_global.h \
		quazip/quazipfileinfo.h \
		quazip/quazipfile.h \
		quazip/quazipnewinfo.h \
		quazip/quazipdir.h \
		quazip/JlCompress.h \
		core/aes.h \
		core/noizecreator.hpp \
		widgets/progressdialog.h \
		widgets/startwindow.h \
		widgets/createcontainerwindow.h \
		widgets/mainwindow.h \
		widgets/archivewindow.h \
		core/directorysizecalculator.h \
		widgets/resizecontainerwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

aes.o: core/aes.cpp core/aes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o aes.o core/aes.cpp

directorysizecalculator.o: core/directorysizecalculator.cpp core/directorysizecalculator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o directorysizecalculator.o core/directorysizecalculator.cpp

fractalcryptcore.o: core/fractalcryptcore.cpp core/fractalcryptcore.h \
		core/quazipfunctions.h \
		quazip/quazip.h \
		quazip/zip.h \
		quazip/ioapi.h \
		quazip/unzip.h \
		quazip/quazip_global.h \
		quazip/quazipfileinfo.h \
		quazip/quazipfile.h \
		quazip/quazipnewinfo.h \
		quazip/quazipdir.h \
		quazip/JlCompress.h \
		core/aes.h \
		core/noizecreator.hpp \
		widgets/progressdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fractalcryptcore.o core/fractalcryptcore.cpp

quazipfunctions.o: core/quazipfunctions.cpp core/quazipfunctions.h \
		quazip/quazip.h \
		quazip/zip.h \
		quazip/ioapi.h \
		quazip/unzip.h \
		quazip/quazip_global.h \
		quazip/quazipfileinfo.h \
		quazip/quazipfile.h \
		quazip/quazipnewinfo.h \
		quazip/quazipdir.h \
		quazip/JlCompress.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o quazipfunctions.o core/quazipfunctions.cpp

archivewindow.o: widgets/archivewindow.cpp widgets/archivewindow.h \
		core/fractalcryptcore.h \
		core/quazipfunctions.h \
		quazip/quazip.h \
		quazip/zip.h \
		quazip/ioapi.h \
		quazip/unzip.h \
		quazip/quazip_global.h \
		quazip/quazipfileinfo.h \
		quazip/quazipfile.h \
		quazip/quazipnewinfo.h \
		quazip/quazipdir.h \
		quazip/JlCompress.h \
		core/aes.h \
		core/noizecreator.hpp \
		widgets/progressdialog.h \
		core/directorysizecalculator.h \
		ui_archivewindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o archivewindow.o widgets/archivewindow.cpp

createcontainerwindow.o: widgets/createcontainerwindow.cpp widgets/createcontainerwindow.h \
		core/fractalcryptcore.h \
		core/quazipfunctions.h \
		quazip/quazip.h \
		quazip/zip.h \
		quazip/ioapi.h \
		quazip/unzip.h \
		quazip/quazip_global.h \
		quazip/quazipfileinfo.h \
		quazip/quazipfile.h \
		quazip/quazipnewinfo.h \
		quazip/quazipdir.h \
		quazip/JlCompress.h \
		core/aes.h \
		core/noizecreator.hpp \
		widgets/progressdialog.h \
		ui_createcontainerwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o createcontainerwindow.o widgets/createcontainerwindow.cpp

mainwindow.o: widgets/mainwindow.cpp widgets/mainwindow.h \
		widgets/createcontainerwindow.h \
		core/fractalcryptcore.h \
		core/quazipfunctions.h \
		quazip/quazip.h \
		quazip/zip.h \
		quazip/ioapi.h \
		quazip/unzip.h \
		quazip/quazip_global.h \
		quazip/quazipfileinfo.h \
		quazip/quazipfile.h \
		quazip/quazipnewinfo.h \
		quazip/quazipdir.h \
		quazip/JlCompress.h \
		core/aes.h \
		core/noizecreator.hpp \
		widgets/progressdialog.h \
		widgets/archivewindow.h \
		core/directorysizecalculator.h \
		widgets/resizecontainerwindow.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o widgets/mainwindow.cpp

progressdialog.o: widgets/progressdialog.cpp widgets/progressdialog.h \
		ui_progressdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o progressdialog.o widgets/progressdialog.cpp

resizecontainerwindow.o: widgets/resizecontainerwindow.cpp widgets/resizecontainerwindow.h \
		core/fractalcryptcore.h \
		core/quazipfunctions.h \
		quazip/quazip.h \
		quazip/zip.h \
		quazip/ioapi.h \
		quazip/unzip.h \
		quazip/quazip_global.h \
		quazip/quazipfileinfo.h \
		quazip/quazipfile.h \
		quazip/quazipnewinfo.h \
		quazip/quazipdir.h \
		quazip/JlCompress.h \
		core/aes.h \
		core/noizecreator.hpp \
		widgets/progressdialog.h \
		ui_resizecontainerwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o resizecontainerwindow.o widgets/resizecontainerwindow.cpp

startwindow.o: widgets/startwindow.cpp widgets/startwindow.h \
		widgets/createcontainerwindow.h \
		core/fractalcryptcore.h \
		core/quazipfunctions.h \
		quazip/quazip.h \
		quazip/zip.h \
		quazip/ioapi.h \
		quazip/unzip.h \
		quazip/quazip_global.h \
		quazip/quazipfileinfo.h \
		quazip/quazipfile.h \
		quazip/quazipnewinfo.h \
		quazip/quazipdir.h \
		quazip/JlCompress.h \
		core/aes.h \
		core/noizecreator.hpp \
		widgets/progressdialog.h \
		widgets/mainwindow.h \
		widgets/archivewindow.h \
		core/directorysizecalculator.h \
		widgets/resizecontainerwindow.h \
		ui_startwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o startwindow.o widgets/startwindow.cpp

JlCompress.o: quazip/JlCompress.cpp quazip/JlCompress.h \
		quazip/quazip.h \
		quazip/zip.h \
		quazip/ioapi.h \
		quazip/unzip.h \
		quazip/quazip_global.h \
		quazip/quazipfileinfo.h \
		quazip/quazipfile.h \
		quazip/quazipnewinfo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o JlCompress.o quazip/JlCompress.cpp

qioapi.o: quazip/qioapi.cpp quazip/ioapi.h \
		quazip/quazip_global.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qioapi.o quazip/qioapi.cpp

quaadler32.o: quazip/quaadler32.cpp quazip/quaadler32.h \
		quazip/quachecksum32.h \
		quazip/quazip_global.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o quaadler32.o quazip/quaadler32.cpp

quacrc32.o: quazip/quacrc32.cpp quazip/quacrc32.h \
		quazip/quachecksum32.h \
		quazip/quazip_global.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o quacrc32.o quazip/quacrc32.cpp

quagzipfile.o: quazip/quagzipfile.cpp quazip/quagzipfile.h \
		quazip/quazip_global.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o quagzipfile.o quazip/quagzipfile.cpp

quaziodevice.o: quazip/quaziodevice.cpp quazip/quaziodevice.h \
		quazip/quazip_global.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o quaziodevice.o quazip/quaziodevice.cpp

quazip.o: quazip/quazip.cpp quazip/quazip.h \
		quazip/zip.h \
		quazip/ioapi.h \
		quazip/unzip.h \
		quazip/quazip_global.h \
		quazip/quazipfileinfo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o quazip.o quazip/quazip.cpp

quazipdir.o: quazip/quazipdir.cpp quazip/quazipdir.h \
		quazip/quazip.h \
		quazip/zip.h \
		quazip/ioapi.h \
		quazip/unzip.h \
		quazip/quazip_global.h \
		quazip/quazipfileinfo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o quazipdir.o quazip/quazipdir.cpp

quazipfile.o: quazip/quazipfile.cpp quazip/quazipfile.h \
		quazip/quazip_global.h \
		quazip/quazip.h \
		quazip/zip.h \
		quazip/ioapi.h \
		quazip/unzip.h \
		quazip/quazipfileinfo.h \
		quazip/quazipnewinfo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o quazipfile.o quazip/quazipfile.cpp

quazipfileinfo.o: quazip/quazipfileinfo.cpp quazip/quazipfileinfo.h \
		quazip/quazip_global.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o quazipfileinfo.o quazip/quazipfileinfo.cpp

quazipnewinfo.o: quazip/quazipnewinfo.cpp quazip/quazipnewinfo.h \
		quazip/quazip_global.h \
		quazip/quazipfileinfo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o quazipnewinfo.o quazip/quazipnewinfo.cpp

unzip.o: quazip/unzip.c quazip/unzip.h \
		quazip/ioapi.h \
		quazip/crypt.h \
		quazip/quazip_global.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o unzip.o quazip/unzip.c

zip.o: quazip/zip.c quazip/zip.h \
		quazip/ioapi.h \
		quazip/crypt.h \
		quazip/quazip_global.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o zip.o quazip/zip.c

qrc_resources.o: qrc_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resources.o qrc_resources.cpp

moc_aes.o: moc_aes.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_aes.o moc_aes.cpp

moc_directorysizecalculator.o: moc_directorysizecalculator.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_directorysizecalculator.o moc_directorysizecalculator.cpp

moc_noizecreator.o: moc_noizecreator.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_noizecreator.o moc_noizecreator.cpp

moc_archivewindow.o: moc_archivewindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_archivewindow.o moc_archivewindow.cpp

moc_createcontainerwindow.o: moc_createcontainerwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_createcontainerwindow.o moc_createcontainerwindow.cpp

moc_resizecontainerwindow.o: moc_resizecontainerwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_resizecontainerwindow.o moc_resizecontainerwindow.cpp

moc_startwindow.o: moc_startwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_startwindow.o moc_startwindow.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_progressdialog.o: moc_progressdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_progressdialog.o moc_progressdialog.cpp

moc_quagzipfile.o: moc_quagzipfile.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_quagzipfile.o moc_quagzipfile.cpp

moc_quaziodevice.o: moc_quaziodevice.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_quaziodevice.o moc_quaziodevice.cpp

moc_quazipfile.o: moc_quazipfile.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_quazipfile.o moc_quazipfile.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/FractalCrypt/bin || mkdir -p $(INSTALL_ROOT)/opt/FractalCrypt/bin
	$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/opt/FractalCrypt/bin/$(QMAKE_TARGET)
	-$(STRIP) $(INSTALL_ROOT)/opt/FractalCrypt/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/FractalCrypt/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/FractalCrypt/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

